version: '3.4'

services:
  categorydb:
    image: mongo

  category.api:
    image: ${DOCKER_REGISTRY-}categoryapi
    build:
      context: .
      dockerfile: src/Services/Category/Category.Api/Dockerfile

volumes:
  mongo_data:
